#!/bin/sh
PHY_INDEX_WPS=auto
PHY_INDEX_BRIDGE=

BRIDGE_ESSID="WPSWAGON"
BRIDGE_ENC="psk" 
BRIDGE_MODE="sta"
BRIDGE_KEY="WPSWAGONKEY"

WAIT_BULLY_NO_PIXIE=3600
WAIT_BULLY=100
WAIT_DHCP=60
PIXIE_ATTEMPS=2
PIXIE_DATE_STEP=300000
WAIT_DHCP_ROUND=1

AFRAID_DNS="http://freedns.afraid.org/dynamic/update.php?"
UPNP_CONFIG="PORT_START;PORT_END;TCP|UDP PORT_START;PORT_END;TCP|UDP"

GWNOTIFY="192.168.2.1"
FALLBACK_WAN_IPS=""

PEERS_NTPD_LOCAL="192.168.2.1"
PEERS_NTPD_INET="4.openwrt.pool.ntp.org 2.openwrt.pool.ntp.org 1.openwrt.pool.ntp.org 3.openwrt.pool.ntp.org"